CREATE TRIGGER TG_PILOTO_TURISTA_BEFORE_INSERT 
    BEFORE INSERT ON EXPEDICAO_TURISTA
    BEGIN
        DECLARE OVERLAP AS VARCHAR(20);
        SELECT PILOTO INTO OVERLAP
        FROM EXPEDICAO
        WHERE NAVE = NEW.NAVE AND DH_INICIO = NEW.DH_INICIO AND PILOTO = NEW.TURISTA  

        IF OVERLAP IS NOT NULL THEN
            RAISE_APPICATION_ERROR(-20001, 'ERRO DE INSERCAO. PILOTO JA REGISTRADO')
        END IF;
    END;

CREATE TRIGGER TG_COLONIA_CONFLICT_BEFORE_INSERT 
    BEFORE INSERT ON COLONIA
    BEGIN
        DECLARE OVERLAP AS VARCHAR(20);
        SELECT FACCAO_NOME INTO OVERLAP
        FROM COLONIA
        WHERE FACCAO_NOME = NEW.FACCAO_NOME AND NOME_PLANETA = NEW.NOME_PLANETA AND 
        ((NEW.DH_INICIO BETWEEN DH_INICIO AND DH_FIM) OR (NEW.DH_FIM BETWEEN DH_INICIO AND DH_FIM))

        IF OVERLAP IS NOT NULL THEN
            RAISE_APPICATION_ERROR(-20001, 'ERRO DE INSERCAO. COLONIA JA REGISTRADA')
        END IF;
    END;