name: SQL Test

on:
  push:

jobs:
  test-database:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_sql
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run SQL Scripts
      run: .github/run_sql_scripts.sh
      env:
        PGPASSWORD: postgres
